### ISSUE TITLE
Fix `cargo run --package gentest`

### ISSUE THREAD

**Issue by TimJentzsch** [DioxusLabs/taffy#65]
The `cargo run --package gentest` command to run the generated tests does not seem to work. Both I and @CobaltCause ran into issues while trying to make it work:

### Discussed in https://github.com/DioxusLabs/sprawl/discussions/46

<div type='discussions-op-text'>

<sup>Originally posted by **TimJentzsch** May 16, 2022</sup>
When using `cargo run --package gentest` to run the tests, I get the following error:

```
   Compiling gentest v0.1.0 (/home/tim/Documents/stretch/scripts/gentest)
    Finished dev [unoptimized + debuginfo] target(s) in 2.16s
     Running `target/debug/gentest`
Starting ChromeDriver 101.0.4951.41 (93c720db8323b3ec10d056025ab95c23a31997c9-refs/branch-heads/4951@{#904}) on port 4444
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
thread 'tokio-runtime-worker-4' panicked at 'unexpected webdriver error; webdriver returned error: unknown error: DevToolsActivePort file doesn't exist', /home/tim/.cargo/registry/src/github.com-1ecc6299db9ec823/fantoccini-0.11.9/src/session.rs:328:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker-3' panicked at 'called `Option::unwrap()` on a `None` value', /home/tim/.cargo/registry/src/github.com-1ecc6299db9ec823/fantoccini-0.11.9/src/session.rs:282:68
```

Did anyone get this to work and might be able to help me out?</div>

**Comment by alice-i-cecile** [comment]
Obsoleted by #141. Discussion about how we should handle testing belongs in #133.
